sCREATE DATABASE QLDKSDI
GO
USE QLDKSDI

CREATE TABLE KhachHang (
	MaKH VARCHAR(10) PRIMARY KEY,
	HoTen VARCHAR(20),
	DiaChi VARCHAR(50),
	CMND VARCHAR(10),
	LoaiKH VARCHAR(10),
	SoDT INT
);

CREATE TABLE HopDong (
	MaHD VARCHAR(10) PRIMARY KEY,
	MaKH VARCHAR(10) FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
	NgayDK SMALLDATETIME,
	TongTK varchar(15),
	ChiPhi INT,
	NgayKyHD SMALLDATETIME	
);

CREATE TABLE TaiKhoan (
	TenTruyCap VARCHAR(15) PRIMARY KEY,
	MatKhau VARCHAR(20),
	Email VARCHAR(20),
	MaHD VARCHAR(10) FOREIGN KEY (MaHD) REFERENCES HopDong(MaHD),
	DiaChiCaiDat VARCHAR(50),
	DiaChiThanhToan VARCHAR(50),
	TrangThai BIT,
);

CREATE TABLE PhieuBao (
	MaPhieu VARCHAR(10) PRIMARY KEY,
	TenTruyCap VARCHAR(15) FOREIGN KEY (TenTruyCap) REFERENCES TaiKhoan(TenTruyCap),
	NgayLap SMALLDATETIME,
	ThangLap VARCHAR(10),
	TongTien INT,
	TinhTrang BIT,
	NgayTT SMALLDATETIME,
	HinhThucTT VARCHAR(10),
	TongTienTT INT
);

CREATE TABLE LoaiTG_TruyCap (
	MaLoai VARCHAR(10) PRIMARY KEY,
	TenLoai VARCHAR(10),
	Gia INT,
	GioBD TIME,
	GioKT TIME
);

CREATE TABLE ChiTiet_TruyCap (
	MaCTTC VARCHAR(10) PRIMARY KEY,
	MaLoai VARCHAR(10) FOREIGN KEY (MaLoai) REFERENCES LoaiTG_TruyCap(MaLoai),
	MaPhieu VARCHAR(10) FOREIGN KEY (MaPhieu) REFERENCES PhieuBao(MaPhieu),
	Ngay SMALLDATETIME,
	TongSoPhut INT,
);
ALTER TABLE ChiTiet_TruyCap 
	ADD CHECK (Ngay < GETDATE())

CREATE TABLE NhanVien (
	MaNhanVien VARCHAR(6) PRIMARY KEY,
	HoTen VARCHAR(20),
	DiaChi VARCHAR(50),
	CMND VARCHAR(10),
	MatKhau VARCHAR(20),
	QuyenHan BIT
)
--- Thêm chi tiết truy cập
insert into NhanVien values ('admin1','Đoàn Nam Minh','Phan Thiet - Bình thuận','232731','3071997',1);